name: Build Docker Image, Generate SBOM, and Run SAST

on:
  push:
    branches: [ master ]

jobs:
  build-sbom-sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest
          push: true

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM from Docker image
        run: |
          syft ${{ secrets.DOCKER_USERNAME }}/juice-shop:latest -o cyclonedx-json > sbom.cdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: juice-shop-sbom
          path: sbom.cdx.json

  semgrep:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout source
        uses: actions/checkout@v4

    
      - name: Install Semgrep
        run: |
          curl -sL https://semgrep.dev/get-semgrep.sh | sh

      - name: Run Semgrep SAST Scan
        run: |
          ./semgrep scan --config auto --output semgrep-results.sarif --sarif

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast-report
          path: semgrep-results.sarif
